### PR TITLE
Fix bugs involving dragging and iframes

### PR DESCRIPTION
**Pull request by psndcsrv**
Here's my proposed fix.

There's 2 parts to it:
1) A pane that gets put over any iframes in the page during a drag so that a drag within the page won't get interrupted.
2) A timeout when the mouse leaves the page during a drag which will end the drag (useful when the embeddable is in an iframe in another page).

@scytacki: What do you think?

### CODE REVIEW

**Comment by psndcsrv** [comment]
The same fix would get applied in embeddable.js in lab-interactives-site.

**Comment by scytacki** [comment]
This looks pretty good to me. 
What happens if you mouse up outside before the timeout and then bring the mouse back in? I'm guessing this will probably not trigger the mouse up, but it seems an unlikely case with a 0.5 second timeout.

**Comment by psndcsrv** [comment]
@scytacki If you leave the iframe, mouse up and move back into the iframe within 0.5 seconds, then it should behave like it currently does -- the mouseup won't be recognized, and the drag will still be happening even though your mouse button isn't down. I felt like half a second was long enough to not mess up accidental drags outside the iframe, but short enough that the odds of the mouseup being missed would be pretty low.

**Comment by scytacki** [comment]
@psndcsrv I had thought you merged this in, so that Evangline could test on interactives-dev. But I see it isn't merged. Did you merge this a different way?

cc @jengoree

**Comment by psndcsrv** [comment]
I realized that the lab-interactives-site version of embeddable.js was the one that would actually be loaded and used on lab.concord.org, so I merged it there. But, I'll merge this too so that they're in sync.

**Pull request merged**
