### PR TITLE
DON'T MERGE: Allow image components to set url relative to interactive json

### PR DESCRIPTION
**Pull request by psndcsrv**
[#90704518]

### CODE REVIEW

**Comment by scytacki** [comment]
@psndcsrv can you test this with the way LARA handles save state. LARA uses `getLearnerUrl` and then the next time this page is visited the learnerUrl of the interactive is loaded instead of the interactive, and then the state is passed in. It seems like the learnerUrl doesn't include the interactive path, so I suspect this pull request will break that interaction (if the interactive has images relative to the interactive).

This http://concord-consortium.github.io/lara-interactive-api/ site might help testing this.  You can see what getLearnerUrl returns, and you can try saving and loading state.

I don't see a good solution to this. If there isn't one, I think it is ok to drop support for interactive relative URLs.

**Comment by scytacki** [comment]
@psndcsrv, because we are trying to get a lab release out, I think we should go with the more conservative approach that doesn't support interactive relative. You can leave this pull request open and just add the page relative code directly to master. To leave this in a nice state it would be good to rebase this wip branch, so it just contains the interactive relative support.

**Comment by psndcsrv** [comment]
@scytacki I agree. I looked at the LARA save state stuff a bit yesterday, and my first impression on that is that it will break the 'interactive' mode as it is now. So I'll rebase this, split it up, and merge the 'page' support.

**Comment by psndcsrv** [comment]
@scytacki OK, I merged in the 'relative to page' work, and have left the 'relative to interactive' work here, to be picked up later.

**Pull request closed without merging**
