### PR TITLE
Enable functionality to use alternative images for Genetics renderer

### PR DESCRIPTION
**Pull request by dstrawberrygirl**
This is a workaround to enable alternative images to be used for for Connected Bio application. I'm not sure there's any other way to specify an image path for this part of Lab, since it's all built-in, so I chose to use the last part of the URL as the common path for Lab and the interactive to identify which resources to display. 

As such, the model on the interactive site has the following imagePath:
`"imagePath": "/models-converted/lab-version/1/md2d/connected-bio/DNA-to-proteins/dna-cbio"`

so Lab uses just the final folder to choose which set of images to use for the renderer.

If there's a better way to do this with minimal changes to Lab let me know!

### CODE REVIEW

**Comment by dstrawberrygirl** [comment]
Thanks for the feedback! pretty much in line with what I was thinking - ideally this would all be in the interactives site, but the whole of the genetics animations as they are now exist baked into Lab. It would take me longer to extract that same functionality and make a new interactive.

> Personally, I'd prefer an explicit option, something like `dnaEngineImagesPath`. If it's `null`, then we use the default set. Otherwise, you can provide a path pointing to some subdirectory in lab-interactives-site or somewhere else. I'd check the implementation of `imagesPath` and ensure we follow the same pattern with relative and absolute paths (and being relative to model files or not).

I was thinking this might be a an alternative / better approach - though since this would involve adding a whole new property to the model for a single case, I wasn't sure if this would be the best approach long term. But I agree it's probably better to keep it separate from the images path. I'll make that change and see how it works out.

**Comment by pjanik** [comment]
I think that if you use the same approach as here:
https://github.com/concord-consortium/lab/blob/master/src/lab/models/md2d/views/images-renderer.js#L177
and 
https://github.com/concord-consortium/lab/blob/master/src/lab/models/md2d/views/images-renderer.js#L182
=> combing `labConfig.modelsRootUrl` + `dnaEngineImagesPath` to get a final path, then it should be easy to move these custom images to lab-interactives-site.

I guess that the default value of `dnaEngineImagesPath` would need to be `null` so we can detect whether it's been provided by user or not. I'd mention in the metadata comments that this path is relative to` modelsRootUrl`.

**Comment by dstrawberrygirl** [comment]
I've incorporated the modelsRootUrl parameter as suggested, though I don't think it's used at this stage. I tried a couple of alternatives, such as using the modelView.url parameter as we do for imagesRenderer, but instead of using the interactive's url, it uses the Lab url so we're back to images within Lab. I'm not sure I can feasibly achieve a better result this iteration.

**Comment by pjanik** [comment]
> but instead of using the interactive's url, it uses the Lab url so we're back to images within Lab.

I guess you got a relative URL, right? Something like:
`"models-converted/lab-version/1/md2d/sam-activities/DNA-to-proteins/page3/page3$0.json"`?
You know that this is actually relative to Lab Interactives Site, not Lab (Framework), right?

Note that `resourcesUrl` function converts all the relative URLs to URLs pointing to `//lab-framework...`. So, if `dnaEngineImagesPath` is defined, you also shouldn't use `resourceUrl` helper for all the paths. You'll have a relative URL and that's all.

But if you can't get that working or run out of time, that's okay.

**Comment by dstrawberrygirl** [comment]
The URLs I got were full URLs - the images one pointed to my local interactive site localhost:9292 whereas the genetics one gave me localhost:9191 for Lab. I'm absolutely agreed we should fix it properly so that it's a clean interactive, but sadly we're out of time this iteration. I'll make sure to reference this PR for when we return to the project later in the year.

**Comment by pjanik** [comment]
Okay 👍 
> gave me localhost:9191 for Lab.

For future reference, your code here is always using `resourceUrl` function and I'm betting that's the actual problem.

**Pull request merged**
