### PR TITLE
Greek translation (for lab strings)

### PR DESCRIPTION
**Pull request by birbilis**

### CODE REVIEW

**Comment by sfentress** [comment]
Hi @birbilis, this looks great, thank you.

You had a question about the `__click_here_link__` in the other thread. You can see the answer in [this part of the localization documentation](https://github.com/concord-consortium/lab/blob/master/developer-doc/localization.md#namespaces-and-special-expressions). It uses the localized value of `click_here`, and makes it a link. Does that answer your question. Does your current Greek value for `click_here` work with that expression.

This looks fine to me, but I just want to check with @ddamelin whether he thinks the example interactives need to be translated too in this same PR.

**Comment by birbilis** [comment]
thanks for the clarification on the click_here, I need to fix _failed_alert then to remove the Greek click word since it will result in it being shown twice. From what I remember I can do more edits and they will be added to the pending pull request (wonder what the check bots do in that case, hope they do run again)

**Comment by birbilis** [comment]
nice, it seems to have caught my change and guess after Travis finishes it will add my fix to the pending pull request (will notice it by the title of that fix mentioning "click_here")

let me know if you need me to translate those models too, was planning to do it separately (with the help of two educators in that field) while working on lab_interactives repo models (guess those samples are exact copies from there? in fact I wonder if a git repo can link/pull files from other repos, wouldn't need to clone the files manually)

**Comment by birbilis** [comment]
strange, although it says again "All check have passed" it doesn't list the latest fix

**Comment by birbilis** [comment]
I closed and reopened the pull request and travis seems to run again, but still at the list of changes at the top I don't see my latest change

**Comment by birbilis** [comment]
I mean it doesn't show this
https://github.com/birbilis/lab/commit/1a27f57bfbdae1909c108fec42afddba70bfb6ea

**Comment by birbilis** [comment]
btw, just in case I checked all the other languages and it seems only me had that confusion with the click_here (didn't see any redundant localized click word at the rest of the translations). If you see the missing commit I mention above, it's just one word removed, if it doesn't show that commit at merge, let me know if you want me to make a new pull request and close this one, or if you can manually edit the commit (I had checked the option to allow it) when merging and remove that redundant Greek click word (spelled "πατήστε")

**Comment by sfentress** [comment]
> I mean it doesn't show this birbilis/lab@1a27f57

GitHub PR conversations can be laid out in a confusing manner, I find. It's chronological, so your commit is visible above -- it's just above your comment that starts with "nice, it seems to have caught my change..." In any case, it's there.

**Comment by ddamelin** [comment]
Regarding translation of example interactives I think that can be done in a separate PR, and you are not required to translate them all (although we appreciate any that you would do). In particular I think "Oil and water" is the one that is currently translated into every localization that Lab knows about. So, please translate that one if possible, and any others you feel would be useful. You are correct that the examples here in Lab are copies of the ones available in lab-interactives-site, so it would be great to put the translations in both places since the hard work of the doing the actual translation would be done already. Thank you very much for your contributions. They are much appreciated.

**Comment by sfentress** [comment]
:+1:

**Comment by birbilis** [comment]
Indeed, it is now showing it among the replies. Almost certain it wasn't showing it before. Strange

**Comment by birbilis** [comment]
Hi @jengoree,
have submitted 5-amino-acids.json on the lab interactives site for now, but there is an issue there that has to be fixed with "gr" country code used instead of "el" language code on the site. The correct one is "el" and that's the one I've used at the lab strings translation. See discussion on this pending issue towards the end of https://github.com/concord-consortium/lab/issues/123

**Pull request merged**
