### PR TITLE
To add hide axis property

### PR DESCRIPTION
**Pull request by rishiloyola**
Hi,
I added new property to hide axis values. I tested it locally for pendulum. Here is the image of it - https://www.flickr.com/photos/130718981@N06/16981255991/player/

### CODE REVIEW

**Comment by sfentress** [comment]
Hi Rishi, I think this also needs a commit to update the lab-grapher submodule, right?

In your local copy, did you do that, or did you just copy and paste the new lab-grapher library?

If you're unsure how to do it, I could add it.

**Comment by rishiloyola** [comment]
Hi Sam,
 Yes, locally I just replaced lab-grapher submodule with the new lab-grapher library.

**Comment by sfentress** [comment]
The lab-grapher project is imported into Lab as a submodule. To update the submodule and commit the change:

```
cd vendor/lab-grapher
git pull origin master
cd -
```

Check to see that the change to lab-grapher looks clean:

`git diff vendor/lab-grapher`

It should be a one-line change that looks something like `Subproject commit 3b17f51ea...` (with no "-dirty" at the end or anything). If it looks ok, commit and push this change to the branch.

**Comment by rishiloyola** [comment]
Hi Sam,
It is showing me error while pushing my commit. It is showing me following error.
https://www.flickr.com/photos/130718981@N06/16372086673/player/
I think so I cant have access key to push my commit. Help me.

**Comment by sfentress** [comment]
This should just be a regular commit to your own branch. It should be identical to all the other commits you've made.

**Comment by rishiloyola** [comment]
Hi,
I updated lab-grapher submodule. Have a look at it.

**Comment by ddamelin** [comment]
@sfentress Can you check out this pull request. I tried to build this branch and I get the error:
```
fatal: reference is not a tree: ba2e76d4e82196068d2a8a5c2819e1b04aaabd97
Unable to checkout 'ba2e76d4e82196068d2a8a5c2819e1b04aaabd97' in submodule path 'vendor/lab-grapher'
```

**Comment by sfentress** [comment]
This doesn't work for me either. 'ba2e..' is not a valid commit in the lab-grapher project.

I guess I can just modify this myself, and pull it in.

**Comment by sfentress** [comment]
Ok, I updated the submodule, rebased the commit and merged it in. I guess because the branch was rebased, the merge doesn't show up in this PR, but you can see it here: 74db928

**Comment by rishiloyola** [comment]
Hi @sfentress 
Thanks for merging it.

**Pull request closed without merging**
