### PR TITLE
Social Media share dialog feature for interactives

### PR DESCRIPTION
**Pull request by ankg**

### CODE REVIEW

**Comment by ddamelin** [comment]
Buttons look nice. The posts always use the same generic text and URL. Would there be a way to incorporate at least the title of the Interactive being shared to the post?

I also noticed that "twitter" initially showed up for me, but now only Facebook and Google Plus do? I don't have a Twitter account. Is the button display dependent on a current session with a particular service? Seems like we would want all of the options there all the time.

Here's where I was testing this build: http://staff.concord.org/~ddamelin/public/index.html

**Comment by ankg** [comment]
I have made the share button script loading faster. I hope it loads well now. That issue persists mainly because the js files of share button's take a lot of time to load hence requests fail sometimes. Earlier, If you reload the page several times, you'll sometimes see all buttons and some are missing at the other times. Hope It'll work better now. Do reply if issues persist.

Also, I'll add interactive name to the posts soon.

**Comment by ddamelin** [comment]
This is working more consistently for me now.

**Comment by ankg** [comment]
So, is it fine now?

**Comment by ddamelin** [comment]
I would like a couple of other folks to take a look before we merge your pull request.

**Comment by emcelroy** [comment]
Hi Aniket,

Thanks for doing this work. I still see the issue with buttons not always appearing unfortunately. Sometimes it's just one button that doesn't appear. Sometimes none of them appear. I'm using Chrome 42 on a Mac.

In general I think it looks good. I'd prefer it if the G+ button were the same height as the Facebook and Twitter buttons, like it is on this page for example: http://concord.org/stem-resources/geniverse

It sounds like you're working on getting the interactive title to incorporate correctly like Dan asked. That'd be good. It'd be really good if you could also get the correct URL in the tweet text. Getting the title and a description incorporated for Facebook and Google+ would be nice as well. That probably requires making each interactive page's HTML title tag include the title of the interactive. For example:

<title>Oil and Water Lab Interactive</title>

and adding a meta description tag (if we have text for it) to the page's <head> section:

<meta name="description" content="Description of interactive goes here. Best if kept under 150 characters." />

It might also require adding Open Graph meta tags to the page's <head> section.

<meta property="og:title" content="Oil and Water Lab Interactive" />
<meta property="og:description" content="Description of interactive goes here. Best if kept under 150 characters." />

It'd be really great if we could also get an og:image tag pointing to a screen shot of the interactive, but that would involve making screen shots of every interactive. I'm not sure if that's too much work or not.

<meta property="og:image" content="/path/to/screen-shot.png" />

Ethan

**Comment by scytacki** [comment]
I don't have time to answer more now. But adding the title and meta info
will be tricky. See this page for a hint why:
https://support.google.com/webmasters/answer/174992?hl=en

--
from my phone

**Comment by scytacki** [comment]
What I was hinting at is this:
The interactive specification is loaded over AJAX based on the `location.hash`.
The social media sites load in the referenced web page, just like google does to search it.  But they typically do not then run the javascript on the page.  If they don't run the javascript then they will not discover the correct page title and meta-information.

I think the best solution to this problem is to stop using AJAX based loading of our interactive.json files when they are on production.   That is a new story though which I just added:
https://www.pivotaltracker.com/story/show/91014434

I don't think it makes sense to add the share links unless at least the title is setup correctly. So in my opinion we should not merge this in until we have solved that.

**Comment by ankg** [comment]
@emcelroy I am unsure why buttons disappear, it works perfectly well on my machine, I'll try looking into it again.

Changed the g+ button to be same size. Corrected the tweet text. Also getting title for twitter and G+. Unable to get image and title in facebook share. I don't think that the only way to show images in shares would be adding meta `og:image` tags to all pages. There must be something better.
I guess the open graph share crawls our page for relevant content. I'll research.

Thanks.

**Comment by ankg** [comment]
@scytacki Sir, You've put a pretty valid point as all of interactions in http://lab-framework.concord.org/  are based on `embeddable.html` and AJAX content isn't scraped by crawlers. Though there are application building tools like [Rendr](https://github.com/rendrjs/rendr) and [Brisket](https://github.com/bloomberg/brisket) but that would be unmanageable work. 

Thinking of solutions. Will comment if I get any. Thanks for giving an insight on this.

**Pull request closed without merging**
