### PR TITLE
 Let authors position slider label to the left and right of the slider

### PR DESCRIPTION
**Pull request by pjanik**
https://www.pivotaltracker.com/story/show/94535800

This feature is quite simple, although implementation is a bit annoying due to our super-flexible-and-scalable layout. Not sure if there is anyone around to review it, though.

### CODE REVIEW

**Comment by scytacki** [comment]
This looks good to me. @psndcsrv do you want to take a look, since you were the last one to touch the slider code.

**Comment by psndcsrv** [comment]
That looks good to me as well.

**Comment by psndcsrv** [comment]
Related question: Did we ever get around to implementing vertical sliders? If so, this (and maybe some of my work?) will need to get reconciled with that...

**Comment by jengoree** [comment]
I don't think we ever merged the GSoC work with the vertical sliders, but I
think we're going to need it soon.


Jen Goree
jgoree@concord.org
Software Portfolio and Project Manager
The Concord Consortium

**Comment by pjanik** [comment]
I was trying to merge it, but finally I gave up when I noticed that the DOM structure is pretty weird (probably due to some complex positioning). Also, the slider component code has grown a lot in the meantime. I'm betting it's better to rewrite code needed to add the vertical orientation.

Another thing is that this kind of work pretty annoying and more complex than it seems to be due to our magic autoscaling feature. I think It costs a lot of dev time and probably in 90% of cases we don't care about it. At the moment it makes sense to maintain that, but if we plan some bigger work on Lab components (or e.g. add a few new ones), I would consider some alternatives.

**Pull request merged**
